# Generated by Django 3.0.8 on 2020-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_model',
            name='img',
        ),
        migrations.AlterField(
            model_name='customers_model',
            name='username',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=20),
        ),
    ]
