# Generated by Django 3.0.6 on 2020-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200822_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecords',
            name='Total',
            field=models.IntegerField(default=0, help_text='Grand Total'),
        ),
    ]
