# Generated by Django 3.0.8 on 2020-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200823_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentrecords',
            name='Total',
            field=models.IntegerField(default=1, help_text='Grand Total'),
        ),
    ]
