# Generated by Django 3.0.8 on 2020-08-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200823_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_model',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RentRecords'),
        ),
    ]
