# Generated by Django 3.0.8 on 2020-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200823_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='customers_model',
            name='username',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=20, primary_key=True, serialize=False),
        ),
    ]
