# Generated by Django 3.0.8 on 2020-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200823_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecords',
            name='username',
            field=models.CharField(default='Username', error_messages={'required': 'Please enter your name'}, max_length=20),
        ),
    ]
