# Generated by Django 3.0.6 on 2020-08-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rentrecords_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers_model',
            name='report',
        ),
        migrations.RemoveField(
            model_name='rentrecords',
            name='username',
        ),
        migrations.AddField(
            model_name='rentrecords',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Customers_model'),
        ),
    ]
