# Generated by Django 3.0.6 on 2020-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200824_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentrecords',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Remaining', 'Remaining')], default='Unpaid', max_length=18),
        ),
    ]
